---
title: "Find cluster of AUT items"
author: "Joshua Ashkinaze"
date: "2023-05-05"
output:
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r, echo=FALSE}
library(lme4)
library(tidyverse)
library(kableExtra)
library(xtable)
library(gtools)
library(readr)
library(vtable)
library(stargazer)
library(ggplot2)
library(ggthemes)
```

# Global Variables

```{r}
set.seed(416)
CLUSTER_SIZE = 5 # how many items to get
```

# Read in Data

```{r make_model}
library(lme4)
library(tidyverse)
library(gtools)
library(readr)
library(vtable)
library(ggplot2)
library(jtools)

df <- read_csv("../../data/prior_responses.csv")
df$prompt <- as.factor(df$prompt)
df$src <- as.factor(df$src)
df <- df %>%
  rename(study = src,
         aut_item = prompt,
         score = target)
scores <- read_csv("../../data/organisciak_gpt_performance.csv") %>% rename(aut_item = prompt, score=target)
```

## Basic Metadata Description

```{r prompts, echo=TRUE}
aut_freqs <- df %>%
  group_by(aut_item) %>%
  summarize(occur = n()) %>%
  ungroup()
n <- nrow(df)
n_ppl <- n_distinct(df$participant)
n_items <- n_distinct(df$aut_item)
n_studies <- n_distinct(df$study)
mean_freq <- round(mean(aut_freqs$occur), 2) 
sd_freq <- round(sd(aut_freqs$occur), 2) 
min_freq <- min(aut_freqs$occur) 
max_freq <- max(aut_freqs$occur) 

result_str <- sprintf("There were %d total responses from %d participants, across %d distinct AUT items and %d distinct studies. Across all studies, scores were normalized from 1-5. The frequency of AUT items (M=%.2f, SD=%.2f) ranged from %d to %d.", n, n_ppl, n_items, n_studies, mean_freq, sd_freq, min_freq, max_freq)

print(result_str)


```

# Originality Distributions

```{r, echo=TRUE}
ggplot(data=df, aes(y=reorder(aut_item, score), x=score)) + 
  geom_boxplot() +
  labs(x = "Score", y = "AUT Item") +
  ggtitle("Distribution of Originality Scores on AUT Items") +
  theme_few()
ggsave(file.path("../../plots/prior_work_aut_dist.png"), dpi = 300, bg = 'transparent')
```

# Performance
```{r overall_performance}
# Calculate the correlation between predicted and actual ratings
correlation <- cor(scores$predicted, scores$score)
print(sprintf("The overall correlation between predicted and actual ratings is %.2f", correlation))
```


```{r per-item, echo=TRUE}
# Calculate correlation by item using dplyr
cor_by_item <- scores %>%
  group_by(aut_item) %>%
  summarize(correlation = cor(predicted, score))

# Merge the data frames
merged_df <- merge(cor_by_item, aut_freqs, by = "aut_item")
colnames(merged_df) <- c("aut_item", "correlation", "frequency")
merged_df <- merged_df %>% 
  arrange(desc(correlation))

colnames(merged_df) <- c("AUT Item", "Classifier Accuracy (r)", "Frequency in Dataset")
# Calculate overall accuracy and 5-item subset accuracy
aut_items <- merged_df[1:CLUSTER_SIZE,]

overall_accuracy <- cor(scores$predicted, scores$score)
subset_accuracy <- mean(aut_items$`Classifier Accuracy (r)`)

# Update caption with sprintf
aut_freq_table <- xtable(merged_df, 
  caption=sprintf("AUT items by frequency of occurrence in dataset and classifier accuracy, where overall accuracy (r) = %.2f, and average accuracy (r) from 5-item subset = %.2f. All data from \\citet{organisciak_beyond_2022}.", overall_accuracy, subset_accuracy), 
  label="aut_desc_stats", 
  include.rownames=FALSE)

print(aut_freq_table, include.rownames=FALSE, sanitize.text.function = function(x){x})

```
# Write items

```{r}
items <- aut_items$`AUT Item`
write.csv(data.frame(aut_item = items), file = "../../data/chosen_aut_items.csv", row.names = FALSE)

# We have 1500 AI responses so let's bootstrap to get 1500 human responses, too
subset_scored <- scores %>% filter(aut_item %in% items)
bootstrap_subset <- subset_scored %>% 
  sample_n(size = 1500, replace = TRUE)
write.csv(bootstrap_subset, file = "../../data/scored_prior_responses.csv", row.names = FALSE)

```


```{r}
correlation_subset <- cor(scores$score[scores$aut_item %in% items], scores$predicted[scores$aut_item %in% items])

ggplot(scores %>% filter(aut_item %in% items ), aes(x = score, y = predicted)) +
 geom_point() +   geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +

  labs(title=sprintf("Originality Classifier Accuracy of 5-Item Subset \n(r= %.2f)", correlation_subset)) +
  xlab("Actual Score") +
  ylab("Predicted Score") +
  theme_nice()
```



